### ISSUE TITLE
Release notes at AMO

### ISSUE THREAD

**Issue by grahamperrin** [hrai/thesaurus-extension#6]
https://addons.mozilla.org/en-GB/firefox/addon/english-thesaurus-synonyms/versions/1.0.3/updateinfo/ is fine (thanks). 

https://addons.mozilla.org/en-GB/firefox/addon/english-thesaurus-synonyms/versions/1.0.4/updateinfo/ and https://addons.mozilla.org/en-GB/firefox/addon/english-thesaurus-synonyms/versions/1.0.5/updateinfo/ are empty and so, notes can not be seen before deciding whether to accept an update: 

![image](https://user-images.githubusercontent.com/192271/93288087-0575fc80-f7d3-11ea-9db1-b9156eda87a4.png)

– and no notes for those two versions at https://addons.mozilla.org/en-GB/firefox/addon/english-thesaurus-synonyms/versions/

**Comment by hrai** [comment]
These versions related to NPM packages upgrade. I've updated the notes.

**Comment by grahamperrin** [comment]
Notes present at `about:addons`. Thanks for the quick fix!

**Comment by grahamperrin** [comment]
Hi, https://addons.mozilla.org/en-GB/firefox/addon/english-thesaurus-synonyms/versions/1.0.7/updateinfo/ is currently empty …
